# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSObuIu-WyS4qsKzRtQOU6pBctC1-6EL
"""

data = input().split()
minimum = int(data[0])
maximum = int(data[0])
for i in data:
  if int(i) > maximum:
    maximum = int(i)
  elif int(i) < minimum:
    minimum = int(i)
print(f'Minimum number is {minimum}')
print(f'Maximum number is {maximum}')