# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-bkseL3xXqlmn9UJAzZXk_klDz9sYLZ
"""

data = input().split()
count = 0
sum=0
for i in data:
  if int(i)<60:
    count+=1
    sum+=int(i)
print(sum/int(len(data)))
print(count)