# -*- coding: utf-8 -*-
"""Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSObuIu-WyS4qsKzRtQOU6pBctC1-6EL
"""

data = input().split()
count = 0
for i in data:
  if int(i)<60:
    count+=1
print(count)